name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  windows:
    runs-on: windows-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Create Build Environment
          run: cmake -E make_directory ${{github.workspace}}/build
        - name: Configure CMake
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        - name: Build
          working-directory: ${{github.workspace}}/build
          shell: bash
          run: cmake --build . --config $BUILD_TYPE
        - name: Test
          working-directory: ${{github.workspace}}/build
          shell: bash
          run: ctest --rerun-failed --output-on-failure -C $BUILD_TYPE
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-12
          sudo apt-get install g++-12
          sudo apt-get install mesa-common-dev
          sudo apt-get install libasound2-dev
          sudo apt-get install libgl1-mesa-dev
          sudo apt-get install libgl1-mesa-glx
          sudo apt-get install libxi-dev
          sudo apt-get install libgtk-3-dev
          sudo apt-get install libssl-dev
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest --rerun-failed --output-on-failure -C $BUILD_TYPE
